version: "3"

services:
  client:
    image: gcontacts-client2ebuild4:latest
    # container_name: client-contactsg
    restart: always
    # env_file: config.env
    # environment:
    #   DATABASE_CLIENT: ${DATABASE_CLIENT}
    #   DATABASE_NAME: ${DATABASE_NAME}
    #   DATABASE_HOST: ${DATABASE_HOST}
    #   DATABASE_PORT: ${DATABASE_PORT}
    #   DATABASE_USERNAME: ${DATABASE_USERNAME}
    #   DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - webappnetwork
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "80:80"
      - "3000:3000"
    working_dir: /client/src/app
    # entrypoint: ["npm", "start"]
    links: 
      - server

  server:
    image: gcontacts-server2ebuild:latest
    container_name: server-contactsg
    restart: always
    env_file: config.env
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - webappnetwork
    depends_on:
      - mongodb
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "5050:5050"

  mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        # command: mongod --noauth --smallfiles
        networks:
            - webappnetwork

networks:
    webappnetwork:
        driver: bridge